name: build-upload-docs
on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-direcotyr: ./docs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build sphinx documentation
      working-direcotyr: ./docs
      run: |
        make html